---
- name: deploy calculator
  hosts: 172.16.185.11
  remote_user: newiiitb
  tasks:
    - name: Install required Python library for Docker
      pip:
        name: docker
        state: present
    - name: pull the image
      docker_image:
        name: "gururajo/mini-project-calculator"
        source: pull
      register: docker_pull_result
    - name: Stop Docker Container
      community.general.docker_container:
        name: calculator
        image: gururajo/mini-project-calculator
        state: absent
      vars:
        container_default_behavior: "compatibility"
    - name: start docker container
      shell: "docker run --name calculator -d -p 9090:8080 gururajo/mini-project-calculator"
